driver:
  name: terraform
  root_module_directory: test/fixtures
  variable_files:
    - test/fixtures/test.tfvars
  verify_version: false # ignore kitchen-terraform supported terraform version check

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: aws-tfe-nlb

suites:
  - name: main
    verifier:
      color: true
      systems:
        - name: local
          backend: local
          controls:
            - targetGroupsARNs
            - loadBalancerDNS
        - name: aws
          backend: aws
          controls:
            - alb
            - tgPort80hc
            - tgPort443hc
            - tgPort8800hc
